//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIMProClient.AIMProService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AIMProService.IAIMProServerService")]
    public interface IAIMProServerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAIMProServerService/login", ReplyAction="http://tempuri.org/IAIMProServerService/loginResponse")]
        bool login(string username, byte[] pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAIMProServerService/login", ReplyAction="http://tempuri.org/IAIMProServerService/loginResponse")]
        System.Threading.Tasks.Task<bool> loginAsync(string username, byte[] pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAIMProServerService/signUp", ReplyAction="http://tempuri.org/IAIMProServerService/signUpResponse")]
        bool signUp(string username, byte[] pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAIMProServerService/signUp", ReplyAction="http://tempuri.org/IAIMProServerService/signUpResponse")]
        System.Threading.Tasks.Task<bool> signUpAsync(string username, byte[] pass);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAIMProServerServiceChannel : AIMProClient.AIMProService.IAIMProServerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AIMProServerServiceClient : System.ServiceModel.ClientBase<AIMProClient.AIMProService.IAIMProServerService>, AIMProClient.AIMProService.IAIMProServerService {
        
        public AIMProServerServiceClient() {
        }
        
        public AIMProServerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AIMProServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AIMProServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AIMProServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool login(string username, byte[] pass) {
            return base.Channel.login(username, pass);
        }
        
        public System.Threading.Tasks.Task<bool> loginAsync(string username, byte[] pass) {
            return base.Channel.loginAsync(username, pass);
        }
        
        public bool signUp(string username, byte[] pass) {
            return base.Channel.signUp(username, pass);
        }
        
        public System.Threading.Tasks.Task<bool> signUpAsync(string username, byte[] pass) {
            return base.Channel.signUpAsync(username, pass);
        }
    }
}
